version: '3.7'

networks:
  web:
    external: true

volumes:
  db: {}
  redis: {}
  storage: {}
  clamav: {}

services:
  app:
    image: stwon/collect
    env_file: .env
    volumes:
      - storage:/app/storage
    restart: always
    networks:
      - web
      - default
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.collect.rule=Host(`your-domain.com`)"
      - "traefik.http.routers.collect.tls.certresolver=default"
  worker:
    image: stwon/collect
    env_file: .env
    volumes:
      - storage:/app/storage
    command: worker
    restart: always
  scheduler:
    image: stwon/collect
    env_file: .env
    volumes:
      - storage:/app/storage
    command: scheduler
    restart: always
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
    restart: always
  redis:
    image: redis:alpine
    volumes:
      - redis:/data
    restart: always
  clam:
    image: stwon/docker-clamav
    volumes:
      - clamav:/data
    restart: always
